### ISSUE TITLE
Bokeh model does not work

### ISSUE THREAD

**Issue by hcl14** [Algolzw/image-restoration-sde#22]
I'm having a trouble making bokeh model work. The corresponding script for this model (`/codes/config/latent_bokeh/test.py`) doesn't seem to be correct - there are multiple places where it fails, can anybody confirm that it should work?

The following output was obtained using these parameters:
- src_lens: 160
- tgt_lens: 14
- disparity: 50

Gradio produces wrong picture with the config `codes/config/latent_bokeh/options/bokeh/test/refusion.yml`:
<img width="1524" alt="Screenshot 2023-06-13 at 0 05 11" src="https://github.com/Algolzw/image-restoration-sde/assets/29576467/8a1c35c9-9913-4734-9413-70619a65dc63">

**Comment by Algolzw** [comment]
Hi, in test config file, you should change the network settings to:
```
network_G:
  which_model: ConditionalNAFNet
  setting:
    img_channel: 4
    width: 64
    enc_blk_nums: [2, 2, 4, 8]
    middle_blk_num: 12
    dec_blk_nums: [2, 2, 2, 2]
```

Moreover, since the bokeh effect transform task is quit different with other tasks, you should also change some functions (with `**kwargs)` in the [sde_utils.py](https://github.com/Algolzw/image-restoration-sde/blob/main/codes/utils/sde_utils.py#L187) as:
```

    def score_fn(self, x, t, **kwargs):
        # need to pre-set mu and score_model
        noise = self.model(x, self.mu, t, **kwargs)
        return self.get_score_from_noise(noise, t)

    def noise_fn(self, x, t, **kwargs):
        # need to pre-set mu and score_model
        return self.model(x, self.mu, t, **kwargs)

    def reverse_sde(self, xt, T=-1, save_states=False, save_dir='sde_state', **kwargs):
        T = self.sample_T if T < 0 else T

        x = xt.clone()
        for t in tqdm(reversed(range(1, T + 1))):
            score = self.score_fn(x, t, **kwargs)
            x = self.reverse_sde_step(x, score, t)
            # x = self.reverse_sde_step_mean(x, score, t)

            if save_states: # only consider to save 100 images
                interval = self.T // 100
                if t % interval == 0:
                    idx = t // interval
                    os.makedirs(save_dir, exist_ok=True)
                    x_L, x_R = x.chunk(2, dim=1)
                    tvutils.save_image(torch.cat([x_L, x_R], dim=3).data, f'{save_dir}/state_{idx}.png', normalize=False)

        return x
```

**Comment by hcl14** [comment]
Sorry, the problem persists. I applied all your changes and tried the image from dataset:

metadata: `00000, Sony50mmf1.8BS, Sony50mmf16.0BS, 35`

**Comment by Algolzw** [comment]
Hi, can you also provide the `refusion.yml` file?

**Comment by hcl14** [comment]
```
name: latent-reffusion-bokeh
suffix: ~  # add suffix to saved images
model: latent_denoising
distortion: bokeh
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4

datasets:
  test1:
    name: Test
    mode: BokehLQ
    dataroot_LQ: /home/x_ziwlu/datasets/ntire2023/bokeh/ntire_val/src
    dataroot_meta: /home/x_ziwlu/datasets/ntire2023/bokeh/ntire_val/meta.txt

#### network structures
network_G:
  which_model: ConditionalNAFNet
  setting:
    img_channel: 4
    width: 64
    enc_blk_nums: [2, 2, 4, 8]
    middle_blk_num: 12
    dec_blk_nums: [2, 2, 2, 2]

network_L:
  which_model: UNet
  setting:
    in_ch: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 4]
    embed_dim: 4


#### path
path:
  pretrain_model_G: pretrained_models/latent-reffusion-bokeh.pth
  pretrain_model_L: pretrained_models/latent-bokeh.pth
```
